import {msg} from "@lingui/core/macro";
import type {MessageDescriptor} from "@lingui/core";

export const districts = ["Mist", "Lavender Beds", "Goblet", "Shirogane", "Empyreum"];

export const worlds: Record<string, string[]> = {
    Aether: ["Adamantoise", "Cactuar", "Faerie", "Gilgamesh", "Jenova", "Midgardsormr", "Sargatanas", "Siren"],
    Crystal: ["Balmung", "Brynhildr", "Coeurl", "Diabolos", "Goblin", "Malboro", "Mateus", "Zalera"],
    Primal: ["Behemoth", "Excalibur", "Exodus", "Famfrit", "Hyperion", "Lamia", "Leviathan", "Ultros"],
    Dynamis: ["Cuchulainn", "Golem", "Halicarnassus", "Kraken", "Maduin", "Marilith", "Rafflesia", "Seraph"],
    Chaos: ["Cerberus", "Louisoix", "Moogle", "Omega", "Phantom", "Ragnarok", "Sagittarius", "Spriggan"],
    Light: ["Alpha", "Lich", "Odin", "Phoenix", "Raiden", "Shiva", "Twintania", "Zodiark"],
    Materia: ["Bismarck", "Ravana", "Sephirot", "Sophia", "Zurvan"],
};

export const scenes: Record<string, MessageDescriptor> = {
    "Nightclub": msg`Nightclub`,
    "Den": msg`Den`,
    "Cafe": msg`Cafe`,
    "Tavern": msg`Tavern`,
    "Inn": msg`Inn`,
    "Lounge": msg`Lounge`,
    "Bath house": msg`Bath house`,
    "Restaurant": msg`Restaurant`,
    "Fightclub": msg`Fightclub`,
    "Casino": msg`Casino`,
    "Shop": msg`Shop`,
    "Maid cafe": msg`Maid cafe / Host club`,
    "Other": msg({message: `Other`, comment: `Venue type: none of the listed categories`}),
};

export const features: Record<string, MessageDescriptor> = {
    "Courtesans": msg`Courtesans`,
    "Gambling": msg`Gambling`,
    "Artists": msg`Artists`,
    "Dancers": msg`Dancers`,
    "Bards": msg`Bards`,
    "Food": msg`Food`,
    "Drink": msg`Drink`,
    "Twitch DJ": msg`Twitch DJ`,
    "Sync DJ": msg`Sync DJ`,
    "Bar": msg`Bar`,
    "Tarot": msg`Tarot`,
    "Pillow": msg`Pillow talk`,
    "Photography": msg`Photography`,
    "Open stage": msg`Open stage`,
    "Void": msg({message: `Void`, comment: `Venue built in the housing void`}),
    "Stylists": msg`Stylists`,
    "Performances": msg`Novel performances`,
    "Giveaways": msg`Giveaways`,
    "Syncshell available": msg`Syncshell available`,
    "VIP": msg`VIP available`,
    "LGBTQIA+": msg`LGBTQIA+ focused`,
    "RP Heavy": msg`IC RP encouraged`,
    "IC RP Only": msg`IC RP only`,
    "24/7 open house": msg`24/7 open house`,
};

export const games: Record<string, MessageDescriptor> = {
    "Triple triad": msg`Triple triad`,
    "Truth or dare": msg`Truth or dare`,
    "Blackjack": msg`Blackjack`,
    "Deathroll": msg`Deathroll`,
    "Texas holdem": msg`Texas holdem`,
    "Bingo": msg`Bingo`,
    "Roulette": msg`Roulette`,
    "Other Games": msg`Other games`,
};

export const tagDescriptions: Record<string, MessageDescriptor> = {
    "Courtesans": msg`The venue offers erotic role-play services in a consensual environment.`,
    "Gambling": msg`The venue offers various games of chance with set amounts of gils and house rules.`,
    "Artists": msg`Artists are present in the venue to offer various custom artwork.`,
    "Dancers": msg`Dancers populate the venue to hype the party and/or host customers.`,
    "Bards": msg`A bard provides theme-based or general music to entertain guests with a selection of songs.`,
    "Food": msg`The venue offers food in their service.`,
    "Drink": msg`The venue offers drinks in their service, this may be soft drinks or include alcohol.`,
    "Twitch DJ": msg`The venue hosts a DJ who provides music in twitch streams and hype the venue.`,
    "Sync DJ": msg`The venue hosts a sync DJ who offers music via synchshells.`,
    "Bar": msg`The venue offers a bar in the environment.`,
    "Tarot": msg`The venue hosts a Tarot Reader who offers to read drawn cards and provide insights about the possible meaning they hold.`,
    "Pillow": msg`The venue offers Pillows who provide a safe, confidential space to promote an SFW companionship for a limited time.`,
    "Photography": msg`The venue hosts photographers who take venue snapshots or more complex gpose of patrons to display in the venue discord and create memories.`,
    "Open stage": msg`The venue offers the stage for a patron to perform to the audience.`,
    "Void": msg`The venue is built in the void; created outside the walls of the house.`,
    "Stylists": msg`The venue hosts stylists who offer a variety of glamour services, including hair styling, makeup, and wardrobe assistance.`,
    "Performances": msg`The venue offers unique schedule performances, this could be SFW (theater, synch dancers, etc) or NSFW (erotic voyeur shows, live BDSM, etc).`,
    "Giveaways": msg`The venue offers giveaways through various channels, in chat, twitch stream or discord.`,
    "Syncshell available": msg`The venue has a syncshell available for guests to join and see each other as they see themselves.`,
    "VIP": msg`The venue offers various perks through VIP tiers. This could include free drinks, gpose, gambling perk or more.`,
    "LGBTQIA+": msg`The venue is a safe space focused on LGBTQIA+.`,
    "RP Heavy": msg`The venue encourages an environment for players to role play as their characters, though interacting as themselves is allowed.`,
    "IC RP Only": msg`The venue offers an environment for players to role play as their characters only, and does not allow open interaction as themselves.`,
    "24/7 open house": msg`The venue allows anyone to visit at anytime, even outside of any scheduled hours`,
    "Triple triad": msg`The venue offers individual or competitive games of Triple Triad via the game interface itself.`,
    "Truth or dare": msg`The venue offers a game of Truth or Dare for whomever feels like joining. Sometimes in private alliance, sometimes venue wide.`,
    "Blackjack": msg`The venue holds a table for players who wish to gamble gil in a game of 21.`,
    "Deathroll": msg`The venue offers individual or competitive game of Deathroll usually with prizes involved.`,
    "Texas holdem": msg`The venue holds a table for players who wish to gamble gil in a game of Texas holdem.`,
    "Bingo": msg`The venue holds a venue wide bingo game, usually with prizes involved.`,
    "Roulette": msg`The venue holds a table for players who wish to gamble gil in a game of Roulette.`,
    "Other Games": msg`The venue offers other unique games.`,
};

export const timeZones: Record<string, MessageDescriptor> = {
    "America/New_York": msg`Eastern Standard Time (EST)`,
    "America/Chicago": msg`Central Standard Time (CST)`,
    "America/Denver": msg`Mountain Standard Time (MST)`,
    "America/Los_Angeles": msg`Pacific Standard Time (PST)`,
    "America/Halifax": msg`Atlantic Standard Time (AST)`,
    "UTC": msg`Server Time (UTC)`,
    "Europe/London": msg`Greenwich Mean Time (GMT)`,
    "Europe/Budapest": msg`Central European Time (CEST)`,
    "Europe/Chisinau": msg`Eastern European Time (EEST)`,
    "Asia/Hong_Kong": msg`Hong Kong Time (HKT)`,
    "Australia/Perth": msg`Australian Western Time (AWST)`,
    "Australia/Adelaide": msg`Australian Central Time (ACST)`,
    "Australia/Sydney": msg`Australian Eastern Time (AEST)`,
};